name: example
description: Showcase App for Fluent UI package for Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluent_ui:
    path: ../
  provider: ^6.0.3
  system_theme: ^2.0.0
  window_manager: ^0.2.7
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.2.0
  url_launcher: ^6.1.5
  clipboard: ^0.1.3
  email_validator: ^2.0.1
  http: ^0.13.4
  flutter_markdown: ^0.6.10+5
  flutter_highlight:
    git:
      url: https://github.com/shreyas1599/highlight.dart.git
      path: flutter_highlight
      ref: b5e7de8bc95f4e8e30534d7b1da5b41979caab01

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#42a5f5"
  image: web/assets/flutter_logo.png