name: fluent_ui
description: Implements Windows UI in Flutter. Based on the official documentation
version: 4.0.1
homepage: https://github.com/bdlukaa/fluent_ui

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  scroll_pos: ^0.3.0

  # Used on icon generator
  recase: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  intl_utils: ^2.7.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/AcrylicNoise.png
  fonts:
    - family: FluentIcons
      fonts:
        - asset: fonts/FluentIcons.ttf